[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "solmate/=lib/solmate/",
    "forge-std/=lib/forge-std/src/",
    "v4-core/=lib/v4-periphery/lib/v4-core/src/",
    "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
    "v4-periphery/=lib/v4-periphery/",
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "ds-test/=lib/solmate/lib/ds-test/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
